#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:18.04

MAINTAINER Netzulo.com

LABEL version="0.0.1-dev3"
LABEL vendor="Netzulo OpenSource Development"
LABEL release-date="2018-08-12"
LABEL version.is-production=""

# ENVironment variables
ENV DEBIAN_FRONTEND noninteractive

# Update SO
RUN apt-get update
RUN apt-get install -y software-properties-common systemd
RUN apt-get clean
# Install
RUN apt-get install -y curl git htop man unzip vim wget telnet net-tools

# ~ install testlink webserver
RUN apt-get install -y nginx

# Add files
## default configuration for webserver
ADD root/default-nginx /etc/nginx/sites-available/default
ADD root/nginx.service /lib/systemd/system/nginx.service
## default configuration for git
ADD root/.gitconfig /root/.gitconfig

# Clone testlink repository
RUN \
  mkdir -p /var/www && \
  cd /var/www && \
  git clone -b master https://github.com/netzulo/testlink-code

# Set environment variables
ENV HOME /root

# Define working directory
WORKDIR /root

# Expose ports for nginx ( just documented, not neccessary )
EXPOSE 80/tcp
EXPOSE 80/udp

# Start new container
CMD ['/bin/bash']

