#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:18.04

MAINTAINER Netzulo.com

LABEL version="0.0.3"
LABEL vendor="Netzulo OpenSource Development"
LABEL release-date="2018-08-30"
LABEL version.is-production=""

# ENVironment variables
ENV DEBIAN_FRONTEND noninteractive

# Update SO
RUN apt-get update
RUN apt-get install -y software-properties-common systemd
RUN apt-get clean
# Install
RUN apt-get install -y curl git htop man unzip vim wget telnet net-tools

# ~ install testlink webserver
RUN apt-get install -y php php-cli php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php php-cgi
RUN apt-get install -y nginx

# Add files
## Starting script
ADD root/entrypoint.sh /root/entrypoint.sh
## default configuration for webserver
ADD root/default-nginx /etc/nginx/sites-available/default
ADD root/nginx.service /lib/systemd/system/nginx.service
### Fix for nginx-php
RUN mkdir -p /run/php/ && touch /run/php/php7.2-fmp.sock
## default configuration for git
ADD root/.gitconfig /root/.gitconfig

# Clone testlink repository
RUN \
  mkdir -p /var/www && \
  cd /var/www && \
  git clone -b testlink_1_9_bootstrapUX https://github.com/netzulo/testlink-code

# Set environment variables
ENV HOME /root

# Define working directory
WORKDIR /root

# Expose ports for nginx ( just documented, not neccessary )
EXPOSE 80/tcp
EXPOSE 80/udp

# Start new container
CMD ['/bin/bash entrypoint.sh']

